package com.example.entity;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Services generated by hbm2java
 */
@Table(value = "services")
public class Services implements java.io.Serializable {

<<<<<<< HEAD
	
	private String serviceCode;
	private String parentServiceCode;
	private String serviceName;
=======
	@PrimaryKey
	private String service_code;
	private String parent_service_code;
	private String service_name;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c

	public Services() {
	}

	public Services(String serviceCode, String parentServiceCode, String serviceName) {
<<<<<<< HEAD
		this.serviceCode = serviceCode;
		this.parentServiceCode = parentServiceCode;
		this.serviceName = serviceName;
	}

	@PrimaryKey
	@Column("service_code")
	public String getServiceCode() {
		return serviceCode;
	}

	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
=======
		this.service_code = serviceCode;
		this.parent_service_code = parentServiceCode;
		this.service_name = serviceName;
	}

	
	@Column("service_code")
	public String getServiceCode() {
		return service_code;
	}

	public void setServiceCode(String serviceCode) {
		this.service_code = serviceCode;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("parent_service_code")
	public String getParentServiceCode() {
<<<<<<< HEAD
		return parentServiceCode;
	}

	public void setParentServiceCode(String parentServiceCode) {
		this.parentServiceCode = parentServiceCode;
=======
		return parent_service_code;
	}

	public void setParentServiceCode(String parentServiceCode) {
		this.parent_service_code = parentServiceCode;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("service_name")
	public String getServiceName() {
<<<<<<< HEAD
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
=======
		return service_name;
	}

	public void setServiceName(String serviceName) {
		this.service_name = serviceName;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	

}
