package com.example.entity;
// Generated Sep 27, 2017 11:56:10 AM by Hibernate Tools 5.2.5.Final

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * ServicesOnProjects generated by hbm2java
 */
<<<<<<< HEAD
@Table(value = "services_on_projects")
public class ServicesOnProjects implements java.io.Serializable {
	
	public ServicesOnProjects(String servicecode, int projectid) {
		super();
		this.servicecode = servicecode;
		this.projectid = projectid;
=======
@Table(value = "service_on_projects")
public class ServicesOnProjects {
	
	@PrimaryKey
	private int service_on_project_id;
	private String service_code;
	private int project_id;
	
	public ServicesOnProjects(int service_on_project_id,String servicecode, int projectid) {
		super();
		this.service_on_project_id = service_on_project_id;
		this.service_code = servicecode;
		this.project_id = projectid;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}
	public ServicesOnProjects() {
		super();
		// TODO Auto-generated constructor stub
	}
	
<<<<<<< HEAD
	@PrimaryKey
	@Column("service_code")
	public String getServicecode() {
		return servicecode;
	}
	public void setServicecode(String servicecode) {
		this.servicecode = servicecode;
	}
	
	@Column("project_id")
	public int getProjectid() {
		return projectid;
	}
	public void setProjectid(int projectid) {
		this.projectid = projectid;
	}
	private String servicecode;
	private int projectid;
	
=======
	
	@Column("service_on_project_id")
	public int getService_on_project_id() {
		return service_on_project_id;
	}
	public void setService_on_project_id(int service_on_project_id) {
		this.service_on_project_id = service_on_project_id;
	}
	
	@Column("service_code")
	public String getService_code() {
		return service_code;
	}
	public void setService_code(String service_code) {
		this.service_code = service_code;
	}
	
	@Column("project_id")
	public int getProject_id() {
		return project_id;
	}
	public void setProject_id(int project_id) {
		this.project_id = project_id;
	}

>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	
	
}
