package com.example.entity;
// Generated Sep 27, 2017 11:56:10 AM by Hibernate Tools 5.2.5.Final

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * StaffOnProjects generated by hbm2java
 */

@Table(value = "staff_on_projects")
public class StaffOnProjects implements java.io.Serializable {

	@PrimaryKey
	private Integer staff_on_project_id;
	private Integer project_id;
	private Integer staff_id;
	private String role_code;
	private String from_datetime;
	private String to_datetime;
	private String hourty_rate;
	
	public Integer getStaff_on_project_id() {
		return staff_on_project_id;
	}
	public void setStaff_on_project_id(Integer staff_on_project_id) {
		this.staff_on_project_id = staff_on_project_id;
	}
	public Integer getProject_id() {
		return project_id;
	}
	public void setProject_id(Integer project_id) {
		this.project_id = project_id;
	}
	public Integer getStaff_id() {
		return staff_id;
	}
	public void setStaff_id(Integer staff_id) {
		this.staff_id = staff_id;
	}
	public String getRole_code() {
		return role_code;
	}
	public void setRole_code(String role_code) {
		this.role_code = role_code;
	}
	public String getFrom_datetime() {
		return from_datetime;
	}
	public void setFrom_datetime(String from_datetime) {
		this.from_datetime = from_datetime;
	}
	public String getTo_datetime() {
		return to_datetime;
	}
	public void setTo_datetime(String to_datetime) {
		this.to_datetime = to_datetime;
	}
	public String getHourty_rate() {
		return hourty_rate;
	}
	public void setHourty_rate(String hourty_rate) {
		this.hourty_rate = hourty_rate;
	}
	public StaffOnProjects(Integer staff_on_project_perioc_id, Integer project_id, Integer staff_id, String role_code,
			String from_datetime, String to_datetime, String hourty_rate) {
		super();
		this.staff_on_project_id = staff_on_project_perioc_id;
		this.project_id = project_id;
		this.staff_id = staff_id;
		this.role_code = role_code;
		this.from_datetime = from_datetime;
		this.to_datetime = to_datetime;
		this.hourty_rate = hourty_rate;
	}
	public StaffOnProjects() {
		super();
		// TODO Auto-generated constructor stub
	}
	

}
