package com.example.entity;
// Generated Sep 27, 2017 11:56:10 AM by Hibernate Tools 5.2.5.Final

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * StaffOnProjects generated by hbm2java
 */

@Table(value = "staff_on_projects")
public class StaffOnProjects implements java.io.Serializable {

<<<<<<< HEAD
	@PrimaryKey
	private Integer staff_on_project_perioc_id;
	private Integer projectsid;
	private String staffid;
	private String refRolescode;
	private String fromDatetime;
	private String toDatetime;
	private String hourtyRate;

	public StaffOnProjects() {
	}

=======
	
	@PrimaryKey
	private Integer staff_on_project_perioc_id;
	private Integer project_id;
	private Integer staff_id;
	private String role_code;
	private String from_datetime;
	private String to_datetime;
	private String hourty_rate;

	public StaffOnProjects() {
	}
	
	@Column("staff_on_project_perioc_id")
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	public Integer getStaffOnProjectPeriocId() {
		return staff_on_project_perioc_id;
	}

	public void setStaffOnProjectPeriocId(Integer staffOnProjectPeriocId) {
		this.staff_on_project_perioc_id = staffOnProjectPeriocId;
	}

	@Column("project_id")
	public Integer getProjectsid() {
<<<<<<< HEAD
		return projectsid;
	}

	public void setProjectsid(Integer projectsid) {
		this.projectsid = projectsid;
	}

	@Column("staff_id")
	public String getStaffid() {
		return staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
=======
		return project_id;
	}

	public void setProjectsid(Integer projectsid) {
		this.project_id = projectsid;
	}

	@Column("staff_id")
	public Integer getStaffid() {
		return staff_id;
	}

	public void setStaffid(Integer staffid) {
		this.staff_id = staffid;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("role_code")
	public String getRefRolescode() {
<<<<<<< HEAD
		return refRolescode;
	}

	public void setRefRolescode(String refRolescode) {
		this.refRolescode = refRolescode;
=======
		return role_code;
	}

	public void setRefRolescode(String refRolescode) {
		this.role_code = refRolescode;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("from_datetime")
	public String getFromDatetime() {
<<<<<<< HEAD
		return fromDatetime;
	}

	public void setFromDatetime(String fromDatetime) {
		this.fromDatetime = fromDatetime;
=======
		return from_datetime;
	}

	public void setFromDatetime(String fromDatetime) {
		this.from_datetime = fromDatetime;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("to_datetime")
	public String getToDatetime() {
<<<<<<< HEAD
		return toDatetime;
	}

	public void setToDatetime(String toDatetime) {
		this.toDatetime = toDatetime;
=======
		return to_datetime;
	}

	public void setToDatetime(String toDatetime) {
		this.to_datetime = toDatetime;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("hourty_rate")
	public String getHourtyRate() {
<<<<<<< HEAD
		return hourtyRate;
	}

	public void setHourtyRate(String hourtyRate) {
		this.hourtyRate = hourtyRate;
	}

	public StaffOnProjects(Integer staffOnProjectPeriocId, Integer projectsid, String staffid, String refRolescode,
			String fromDatetime, String toDatetime, String hourtyRate) {
		super();
		this.staff_on_project_perioc_id = staffOnProjectPeriocId;
		this.projectsid = projectsid;
		this.staffid = staffid;
		this.refRolescode = refRolescode;
		this.fromDatetime = fromDatetime;
		this.toDatetime = toDatetime;
		this.hourtyRate = hourtyRate;
=======
		return hourty_rate;
	}

	public void setHourtyRate(String hourtyRate) {
		this.hourty_rate = hourtyRate;
	}

	public StaffOnProjects(Integer staffOnProjectPeriocId, Integer projectsid, Integer staffid, String refRolescode,
			String fromDatetime, String toDatetime, String hourtyRate) {
		super();
		this.staff_on_project_perioc_id = staffOnProjectPeriocId;
		this.project_id = projectsid;
		this.staff_id = staffid;
		this.role_code = refRolescode;
		this.from_datetime = fromDatetime;
		this.to_datetime = toDatetime;
		this.hourty_rate = hourtyRate;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	

}
