package com.example.entity;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Staff generated by hbm2java
 */
@Table(value = "staff")
public class Staff implements java.io.Serializable {
<<<<<<< HEAD

	@PrimaryKey
	private Integer staff_id;
=======
	@PrimaryKey
	private Integer staff_id;
	
	private String staff_name;
	private String gender_MF;
	private String date_of_birth;
	private String daily_cost;
	private String daily_rate;
	private String date_joined;
	private String date_left;
	private String other_staff_details;
	//private Set<StaffOnProjects> staffOnProjectses = new HashSet<StaffOnProjects>(0);

	public Staff() {
	}

>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	public Staff(Integer staff_id, String staffName, String genderMf, String dateOfBirth, String dailyCost,
			String dailyRate, String dateJoined, String dateLeft, String otherStaffDetails) {
		super();
		this.staff_id = staff_id;
<<<<<<< HEAD
		this.staffName = staffName;
		this.genderMf = genderMf;
		this.dateOfBirth = dateOfBirth;
		this.dailyCost = dailyCost;
		this.dailyRate = dailyRate;
		this.dateJoined = dateJoined;
		this.dateLeft = dateLeft;
		this.otherStaffDetails = otherStaffDetails;
	}

	private String staffName;
	private String genderMf;
	private String dateOfBirth;
	private String dailyCost;
	private String dailyRate;
	private String dateJoined;
	private String dateLeft;
	private String otherStaffDetails;
	//private Set<StaffOnProjects> staffOnProjectses = new HashSet<StaffOnProjects>(0);

	public Staff() {
=======
		this.staff_name = staffName;
		this.gender_MF = genderMf;
		this.date_of_birth = dateOfBirth;
		this.daily_cost = dailyCost;
		this.daily_rate = dailyRate;
		this.date_joined = dateJoined;
		this.date_left = dateLeft;
		this.other_staff_details = otherStaffDetails;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	public Staff(String staffName, String genderMf, String dateOfBirth, String dailyCost, String dailyRate,
			String dateJoined, String dateLeft, String otherStaffDetails) {
<<<<<<< HEAD
		this.staffName = staffName;
		this.genderMf = genderMf;
		this.dateOfBirth = dateOfBirth;
		this.dailyCost = dailyCost;
		this.dailyRate = dailyRate;
		this.dateJoined = dateJoined;
		this.dateLeft = dateLeft;
		this.otherStaffDetails = otherStaffDetails;
	}

	@PrimaryKey
=======
		this.staff_name = staffName;
		this.gender_MF = genderMf;
		this.date_of_birth = dateOfBirth;
		this.daily_cost = dailyCost;
		this.daily_rate = dailyRate;
		this.date_joined = dateJoined;
		this.date_left = dateLeft;
		this.other_staff_details = otherStaffDetails;
	}

	
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	@Column("staff_id")
	public Integer getStaffId() {
		return staff_id;
	}

	public void setStaffId(Integer staffId) {
		this.staff_id = staffId;
	}

	@Column("staff_name")
	public String getStaffName() {
<<<<<<< HEAD
		return staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
=======
		return staff_name;
	}

	public void setStaffName(String staffName) {
		this.staff_name = staffName;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}
	

	@Column("gender_MF")
	public String getGenderMf() {
<<<<<<< HEAD
		return genderMf;
	}

	public void setGenderMf(String genderMf) {
		this.genderMf = genderMf;
=======
		return gender_MF;
	}

	public void setGenderMf(String genderMf) {
		this.gender_MF = genderMf;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("date_of_birth")
	public String getDateOfBirth() {
<<<<<<< HEAD
		return dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
=======
		return date_of_birth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.date_of_birth = dateOfBirth;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("daily_cost")
	public String getDailyCost() {
<<<<<<< HEAD
		return dailyCost;
	}

	public void setDailyCost(String dailyCost) {
		this.dailyCost = dailyCost;
=======
		return daily_cost;
	}

	public void setDailyCost(String dailyCost) {
		this.daily_cost = dailyCost;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("daily_rate")
	public String getDailyRate() {
<<<<<<< HEAD
		return dailyRate;
	}

	public void setDailyRate(String dailyRate) {
		this.dailyRate = dailyRate;
=======
		return daily_rate;
	}

	public void setDailyRate(String dailyRate) {
		this.daily_rate = dailyRate;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("date_joined")
	public String getDateJoined() {
<<<<<<< HEAD
		return dateJoined;
	}

	public void setDateJoined(String dateJoined) {
		this.dateJoined = dateJoined;
=======
		return date_joined;
	}

	public void setDateJoined(String dateJoined) {
		this.date_joined = dateJoined;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("date_left")
	public String getDateLeft() {
<<<<<<< HEAD
		return dateLeft;
	}

	public void setDateLeft(String dateLeft) {
		this.dateLeft = dateLeft;
=======
		return date_left;
	}

	public void setDateLeft(String dateLeft) {
		this.date_left = dateLeft;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	@Column("other_staff_details")
	public String getOtherStaffDetails() {
<<<<<<< HEAD
		return otherStaffDetails;
	}

	public void setOtherStaffDetails(String otherStaffDetails) {
		this.otherStaffDetails = otherStaffDetails;
=======
		return other_staff_details;
	}

	public void setOtherStaffDetails(String otherStaffDetails) {
		this.other_staff_details = otherStaffDetails;
>>>>>>> 53a0f3d2b1b2dcfccaac2aad8333ae9f2c17535c
	}

	

}
