package com.example.entity;

import java.util.UUID;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Clients generated by hbm2java
 */

@Table(value = "clients")
public class Clients implements java.io.Serializable {

	
	@PrimaryKey
	private UUID client_id;
	private UUID currency_code;
	private String client_name;
	private String client_from_date;
	private String kpi_avg_billable_rate;
	private String kpi_billings_to_date;
	private String kpi_client_project_count;
	private String other_client_details;
	//private Set<Projects> projectses = new HashSet<Projects>(0);
	//private ClientAddresses clientAddresses;

	
	
	@Column("client_id")
	public UUID getClientId() {
		return client_id;
	}

	public void setClientId(UUID clientId) {
		this.client_id = clientId;
	}

	@Column("client_id")
	public UUID getRefCurenciescode() {
		return currency_code;
	}

	public void setRefCurenciescode(UUID refCurencies) {
		this.currency_code = refCurencies;
	}

	@Column("client_name")
	public String getClientName() {
		return client_name;
	}

	public void setClientName(String clientName) {
		this.client_name = clientName;
	}

	@Column("client_id")
	public String getClientFromDate() {
		return client_from_date;
	}

	public void setClientFromDate(String clientFromDate) {
		this.client_from_date = clientFromDate;
	}

	@Column("kpi_avg_billable_rate")
	public String getKpiAvgBillableRate() {
		return kpi_avg_billable_rate;
	}

	public void setKpiAvgBillableRate(String kpiAvgBillableRate) {
		this.kpi_avg_billable_rate = kpiAvgBillableRate;
	}

	@Column("kpi_billings_to_date")
	public String getKpiBillingsToDate() {
		return kpi_billings_to_date;
	}

	public void setKpiBillingsToDate(String kpiBillingsToDate) {
		this.kpi_billings_to_date = kpiBillingsToDate;
	}

	@Column("kpi_client_project_count")
	public String getKpiClientProjectCount() {
		return kpi_client_project_count;
	}

	public void setKpiClientProjectCount(String kpiClientProjectCount) {
		this.kpi_client_project_count = kpiClientProjectCount;
	}

	@Column("other_client_details")
	public String getOtherClientDetails() {
		return other_client_details;
	}

	public void setOtherClientDetails(String otherClientDetails) {
		this.other_client_details = otherClientDetails;
	}


	public Clients() {
		
		client_id= UUID.randomUUID();
	}

	public Clients(UUID refCurencies, String clientName, String clientFromDate,
			String kpiAvgBillableRate, String kpiBillingsToDate, String kpiClientProjectCount,
			String otherClientDetails) {
		this.currency_code = refCurencies;
		this.client_name = clientName;
		this.client_from_date = clientFromDate;
		this.kpi_avg_billable_rate = kpiAvgBillableRate;
		this.kpi_billings_to_date = kpiBillingsToDate;
		this.kpi_client_project_count = kpiClientProjectCount;
		this.other_client_details = otherClientDetails;
	}
	
}
