package com.example.entity;

import java.util.UUID;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Projects generated by hbm2java
 */
@Table(value = "projects")
public class Projects implements java.io.Serializable {

	@PrimaryKey
	private UUID project_id;
	private UUID client_id;
	private String project_name;
	private String project_start_date;
	private String project_end_date;
	private String project_description;
	private String other_project_details;
//	private Set<StaffOnProjects> staffOnProjectses = new HashSet<StaffOnProjects>(0);
//	private Set<StaffOnProjects> staffOnProjectses_1 = new HashSet<StaffOnProjects>(0);

	public Projects() {
		project_id = UUID.randomUUID();
	}

	public Projects(UUID clients, String projectName, String projectStartDate, String projectEndDate,
			String projectDescription, String otherProjectDetails) {
		this.client_id = clients;
		this.project_name = projectName;
		this.project_start_date = projectStartDate;
		this.project_end_date = projectEndDate;
		this.project_description = projectDescription;
		this.other_project_details = otherProjectDetails;
	}
	

	

	
	@Column("project_id")
	public UUID getProjectId() {
		return this.project_id;
	}

	public void setProjectId(UUID projectId) {
		this.project_id = projectId;
	}

	@Column("client_id")
	public UUID getClients() {
		return client_id;
	}

	public void setClients(UUID clients) {
		this.client_id = clients;
	}
	@Column("project_name")
	public String getProjectName() {
		return project_name;
	}

	public void setProjectName(String projectName) {
		this.project_name = projectName;
	}
	@Column("project_start_date")
	public String getProjectStartDate() {
		return project_start_date;
	}

	public void setProjectStartDate(String projectStartDate) {
		this.project_start_date = projectStartDate;
	}

	@Column("project_end_date")
	public String getProjectEndDate() {
		return project_end_date;
	}

	public void setProjectEndDate(String projectEndDate) {
		this.project_end_date = projectEndDate;
	}

	@Column("project_description")
	public String getProjectDescription() {
		return project_description;
	}

	public void setProjectDescription(String projectDescription) {
		this.project_description = projectDescription;
	}

	@Column("other_project_details")
	public String getOtherProjectDetails() {
		return other_project_details;
	}

	public void setOtherProjectDetails(String otherProjectDetails) {
		this.other_project_details = otherProjectDetails;
	}
	
	

}
