package com.example.entity;

import java.util.UUID;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Staff generated by hbm2java
 */
@Table(value = "staff")
public class Staff implements java.io.Serializable {
	
	@PrimaryKey
	private UUID staff_id;
	private String staff_name;
	private String gender_MF;
	private String date_of_birth;
	private String daily_cost;
	private String daily_rate;
	private String date_joined;
	private String date_left;
	private String other_staff_details;
	//private Set<StaffOnProjects> staffOnProjectses = new HashSet<StaffOnProjects>(0);

	public Staff() {
		this.staff_id=UUID.randomUUID();
	}



	public Staff(String staffName, String genderMf, String dateOfBirth, String dailyCost, String dailyRate,
			String dateJoined, String dateLeft, String otherStaffDetails) {
		this.staff_name = staffName;
		this.gender_MF = genderMf;
		this.date_of_birth = dateOfBirth;
		this.daily_cost = dailyCost;
		this.daily_rate = dailyRate;
		this.date_joined = dateJoined;
		this.date_left = dateLeft;
		this.other_staff_details = otherStaffDetails;
	}

	
	@Column("staff_id")
	public UUID getStaffId() {
		return staff_id;
	}

	public void setStaffId(UUID staffId) {
		this.staff_id = staffId;
	}

	@Column("staff_name")
	public String getStaffName() {
		return staff_name;
	}

	public void setStaffName(String staffName) {
		this.staff_name = staffName;
	}
	

	@Column("gender_MF")
	public String getGenderMf() {
		return gender_MF;
	}

	public void setGenderMf(String genderMf) {
		this.gender_MF = genderMf;
	}

	@Column("date_of_birth")
	public String getDateOfBirth() {
		return date_of_birth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.date_of_birth = dateOfBirth;
	}

	@Column("daily_cost")
	public String getDailyCost() {
		return daily_cost;
	}

	public void setDailyCost(String dailyCost) {
		this.daily_cost = dailyCost;
	}

	@Column("daily_rate")
	public String getDailyRate() {
		return daily_rate;
	}

	public void setDailyRate(String dailyRate) {
		this.daily_rate = dailyRate;
	}

	@Column("date_joined")
	public String getDateJoined() {
		return date_joined;
	}

	public void setDateJoined(String dateJoined) {
		this.date_joined = dateJoined;
	}

	@Column("date_left")
	public String getDateLeft() {
		return date_left;
	}

	public void setDateLeft(String dateLeft) {
		this.date_left = dateLeft;
	}

	@Column("other_staff_details")
	public String getOtherStaffDetails() {
		return other_staff_details;
	}

	public void setOtherStaffDetails(String otherStaffDetails) {
		this.other_staff_details = otherStaffDetails;
	}

	

}
